inherit: base
name: "33_ugh_d128_try"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined"
  sampler_power: 1.0

model:
  d_model: 256
  n_heads: 4
  n_encoder_layers: 6
  n_decoder_layers: 6
  latent_dim: 128
  beta_end: 0.2
  free_bits: 6

trainer:
  max_epochs: 2
