inherit: default_256
name: "45_d128_b50_baseline_smaller"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined_capped_50k"
  sampler_power: 1.0

model:
  latent_dim: 128
  beta_end: 0.2
  free_bits: 6
  beta_warmup_steps: 100000
  dropout: 0.2
  n_encoder_layers: 2
  n_decoder_layers: 2

trainer:
  max_epochs: 5
