inherit: default_1024
name: "45_d128_b50_baseline_smaller"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined_capped_50k"
  sampler_power: 1.0

model:
  beta_end: 0.2
  free_bits: 48

trainer:
  max_epochs: 5
