inherit: default_512
name: "56_like_54_adjusted_free_bits"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined"

model:
  latent_dim: 128
  beta_end: 0.2
  free_bits: 6
  beta_warmup_steps: 100000

trainer:
  max_epochs: 1
