inherit: default_512
name: "65_like_53_2epochs"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined"

model:
  beta_end: 0.2
  free_bits: 24
  beta_warmup_steps: 100000

trainer:
  max_epochs: 2
