inherit: default_512
name: "74_like_65_beta_0.6_warmedup"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined"

model:
  beta_end: 0.6
  free_bits: 24
  beta_warmup_steps: 300000

trainer:
  max_epochs: 2
