inherit: base
name: "36_ugh_d32_try_wrsp1_higher_beta"

data:
  ds_path: "/home/christian/vae/data_nb_1b_combined"
  sampler_power: 1.0

model:
  d_model: 256
  n_heads: 4
  n_encoder_layers: 6
  n_decoder_layers: 6
  latent_dim: 32
  beta_end: 1.0
  free_bits: 2

trainer:
  max_epochs: 2
